version: '2'

services:

    ############################################################################
    # Nginx Load Balancer
    # proxy server that works with out application (php7-fpm)
    ############################################################################
    nginxlb:
        image: nginx:alpine
        ports:
            - "8080:80"
        mem_limit: 1024m
        volumes:
            - ./:/var/www/
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        links:
            - php

    ###########################################################################
    # PHP 7.2 FPM
    ###########################################################################
    php:
        image: butuzov/php:7.1
        mem_limit: 1024m
        volumes:
           - ./:/var/www/
        links:
            - mysql
    ############################################################################
    # MySQL 5.7
    ############################################################################
    mysql:
        image: mysql:5.7
        mem_limit: 1024m
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: user
            MYSQL_PASSWORD: password
